# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('committeeid', models.CharField(max_length=9)),
                ('committeename', models.CharField(max_length=200)),
                ('street1', models.CharField(max_length=34)),
                ('street2', models.CharField(max_length=34)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.IntegerField()),
                ('treasurerlastname', models.CharField(max_length=30)),
                ('treasurerfirstname', models.CharField(max_length=20)),
                ('treasurermiddlename', models.CharField(max_length=20)),
                ('treasurerprefix', models.CharField(max_length=10)),
                ('treasurersuffix', models.CharField(max_length=10)),
                ('email_on_file', models.TextField(default='-', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('isdeleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Committee',
                'verbose_name_plural': 'Committee',
            },
        ),
    ]
